Snapshot test
gsmalik030/Math-Magicians pull request #6
Opened 2023-02-22 12:53 UTC by Victoria129

- [ ] I have added a snapshot tests file to tests.

2023-02-22 13:24 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @Victoria129 and @gsmalik030,

Nice job, you are almost there.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-22 13:24 UTC, Omar-Muhamad commented on src/__tests__/calculate.test.js
> +// import operate from '../logic/operate';
- [ ] Please remove eslint disablement line and try to fix linters errors yourself. 
[hint:] I removed this line and there is no error found.

- [ ] Please remove any commented(unused) code like line 3 to make your code clean.

2023-02-22 13:24 UTC, Omar-Muhamad commented on src/__tests__/snapshottests.test.js
> +  });
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/project_tests.md#:~:text=js%20using%20Jest.-,Create%20unit%20tests%20for%20all%20React%20components%3A,Use%20Jest%20snapshots%20to%20test%20the%20components.,-Use%20React%20Testing), Please add screenshot tests for the `Calculator` and `navbar` components as you did with `home` and `quote` components.

2023-02-22 14:16 UTC, youmari requested changes
Hi @Victoria129 @gsmalik030 , 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights 
✔️ Clean code 
✔️ PRO PR

## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-02-22 14:16 UTC, youmari commented on src/__tests__/snapshottests.test.js
> +    const navview = render(<Navbar />);
- [ ] Nice adding the required changes by the previous reviewer however  one of the tests is failing please make sure to fix it 
<img width="906" alt="Screenshot 2023-02-22 at 15 14 09" src="https://user-images.githubusercontent.com/61790587/220647212-f1b94068-b0f9-46d2-9904-6c9a6565caec.png">

2023-02-23 09:59 UTC, Lucas-Masaba approved these changes
# Hello @Victoria129  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
- All tests are passing ✔️ 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 10:51 UTC, merged